In [2]:
# Import our dependencies
#from sklearn.model_selection import train_test_split
#from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import numpy as np
#import tensorflow as tf
from pathlib import Path
import os
import warnings
warnings.filterwarnings("ignore")

In [5]:
#  Import and read the charity_data.csv.
ufo = pd.read_csv("/Users/katiebernstein/Downloads/nuforc_reports.csv")
#ufo.head()
#ufo_count
#ufo_columns
ufo_df = ufo
#ufo_df.dtypes

In [6]:
# Fiter file to State of Arizona
newufo_df = ufo_df[(ufo_df.state == "AZ")]
newufo_df

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
60,"When we were about 17-18, a friend and I had j...",Encinitas,AZ,1973-11-03T15:00:00,disk,10 seconds,Occurred : 11/3/1973 15:00 (Entered as : 11/0...,http://www.nuforc.org/webreports/154/S154888.html,"When we were about 17-18, a friend and I had j...",2020-04-09T00:00:00,NaN,NaN
117,Fleet of moving stars. ((Starlink satellites?)),Litchfield Park,AZ,2020-04-17T20:00:00,light,1 hour,Occurred : 4/17/2020 20:00 (Entered as : 04/1...,http://www.nuforc.org/webreports/155/S155338.html,Fleet of moving stars Looked like moving stars...,2020-06-25T00:00:00,33.517800,-112.366700
125,Crazy light show! ((Starlink satellites?)),Tucson,AZ,2020-04-15T20:30:00,light,20 minutes,Occurred : 4/15/2020 20:30 (Entered as : 4/15...,http://www.nuforc.org/webreports/155/S155177.html,Crazy light show! A series of lights eminating...,2020-06-25T00:00:00,32.259941,-110.927542
134,Star looking ufo in sky starts to move then di...,Phoenix,AZ,2020-04-12T01:00:00,other,5-7 minutes,Occurred : 4/12/2020 01:00 (Entered as : 04/1...,http://www.nuforc.org/webreports/154/S154998.html,Star looking ufo in sky starts to move then di...,2020-06-25T00:00:00,33.535381,-112.049460
145,"Saw a bright, star like object, very high up, ...",Tucson,AZ,2020-03-29T21:00:00,circle,2 hours,Occurred : 3/29/2020 21:00 (Entered as : 03/2...,http://www.nuforc.org/webreports/154/S154641.html,"Saw a bright, star like object, very high up, ...",2020-06-25T00:00:00,32.259941,-110.927542
...,...,...,...,...,...,...,...,...,...,...,...,...
136848,Tonopah Arizona lights,Tonopah,AZ,2020-07-23T19:30:00,fireball,1 minute,Occurred : 7/23/2020 19:30 (Entered as : 07/2...,http://www.nuforc.org/webreports/158/S158188.html,Tonopah Arizona lights It was in the afternoon...,2020-08-06T00:00:00,33.577800,-113.023400
136866,MADAR Node 74,Show Low,AZ,2020-06-12T13:46:00,NaN,NaN,Occurred : 6/12/2020 13:46 (Entered as : 06/1...,http://www.nuforc.org/webreports/157/S157391.html,MADAR Node 74,2020-07-09T00:00:00,34.234662,-110.075197
136883,Tonopah Arizona lights,Tonopah,AZ,2020-07-23T19:30:00,fireball,1 minute,Occurred : 7/23/2020 19:30 (Entered as : 07/2...,http://www.nuforc.org/webreports/157/S157699.html,Tonopah Arizona lights It was in the afternoon...,2020-07-23T00:00:00,33.577800,-113.023400
136897,It was about 2:15am to 2:30am I look up in the...,Scottsdale,AZ,2019-07-08T02:15:00,circle,15 min,Occurred : 7/8/2019 02:15 (Entered as : 07/08...,http://www.nuforc.org/webreports/147/S147747.html,It was about 2:15am to 2:30am I look up in the...,2019-07-25T00:00:00,33.564138,-111.905083
136909,Ring Light UFO expanding in and out,Gilbert,AZ,2019-04-01T23:00:00,circle,2 minutes,Occurred : 4/1/2019 23:00 (Entered as : 04/01...,http://www.nuforc.org/webreports/162/S162054.html,Ring Light UFO expanding in and out I was taki...,2021-03-02T00:00:00,33.339601,-111.781265

In [7]:
#look at State value counts for binning
newufo_count = newufo_df.state.value_counts()
newufo_count

AZ    4625
Name: state, dtype: int64

In [8]:
# Find null values
for column in newufo_df.columns:
    print(f"Column {column} has {newufo_df[column].isnull().sum()} null values")

Column summary has 2 null values
Column city has 7 null values
Column state has 0 null values
Column date_time has 25 null values
Column shape has 176 null values
Column duration has 203 null values
Column stats has 0 null values
Column report_link has 0 null values
Column text has 2 null values
Column posted has 25 null values
Column city_latitude has 619 null values
Column city_longitude has 619 null values

In [9]:
# drop null rows for date_time, latitude and longitude only which are float64   NaN
#newufo_df.dropna(subset=newufo_df.select_dtypes(include=np.number).columns, how='all')
newufo_df1 = newufo_df.dropna(subset=["city_latitude","city_longitude","date_time"])

In [10]:
# Remove columns not needed
newufo_df1.drop(columns=["report_link"], inplace=True)
newufo_df1.head()

,summary,city,state,date_time,shape,duration,stats,text,posted,city_latitude,city_longitude
117,Fleet of moving stars. ((Starlink satellites?)),Litchfield Park,AZ,2020-04-17T20:00:00,light,1 hour,Occurred : 4/17/2020 20:00 (Entered as : 04/1...,Fleet of moving stars Looked like moving stars...,2020-06-25T00:00:00,33.517800,-112.366700
125,Crazy light show! ((Starlink satellites?)),Tucson,AZ,2020-04-15T20:30:00,light,20 minutes,Occurred : 4/15/2020 20:30 (Entered as : 4/15...,Crazy light show! A series of lights eminating...,2020-06-25T00:00:00,32.259941,-110.927542
134,Star looking ufo in sky starts to move then di...,Phoenix,AZ,2020-04-12T01:00:00,other,5-7 minutes,Occurred : 4/12/2020 01:00 (Entered as : 04/1...,Star looking ufo in sky starts to move then di...,2020-06-25T00:00:00,33.535381,-112.049460
145,"Saw a bright, star like object, very high up, ...",Tucson,AZ,2020-03-29T21:00:00,circle,2 hours,Occurred : 3/29/2020 21:00 (Entered as : 03/2...,"Saw a bright, star like object, very high up, ...",2020-06-25T00:00:00,32.259941,-110.927542
149,Strange shaped craft,Gilbert,AZ,2019-12-13T22:15:00,other,3 minutes,Occurred : 12/13/2019 22:15 (Entered as : 12/...,strange shaped craft I went to my car to pick ...,2020-06-25T00:00:00,33.339601,-111.781265

In [11]:
# find duplicate entries
print(f"Duplicate entries: {newufo_df1.duplicated().sum()}")

Duplicate entries: 0

In [12]:
# convert date to datestri
newufo_df1["date_time"]
newufo_df1["date_time"].str.split("T", expand=True)

                 0         1
117     2020-04-17  20:00:00
125     2020-04-15  20:30:00
134     2020-04-12  01:00:00
145     2020-03-29  21:00:00
149     2019-12-13  22:15:00
...            ...       ...
136848  2020-07-23  19:30:00
136866  2020-06-12  13:46:00
136883  2020-07-23  19:30:00
136897  2019-07-08  02:15:00
136909  2019-04-01  23:00:00

[3988 rows x 2 columns]

In [13]:
newcolumnlist = ["date_str", "time_str"]
newufo_df1[newcolumnlist] = newufo_df1["date_time"].str.split("T", expand=True)
newufo_df1

,summary,city,state,date_time,shape,duration,stats,text,posted,city_latitude,city_longitude,date_str,time_str
117,Fleet of moving stars. ((Starlink satellites?)),Litchfield Park,AZ,2020-04-17T20:00:00,light,1 hour,Occurred : 4/17/2020 20:00 (Entered as : 04/1...,Fleet of moving stars Looked like moving stars...,2020-06-25T00:00:00,33.517800,-112.366700,2020-04-17,20:00:00
125,Crazy light show! ((Starlink satellites?)),Tucson,AZ,2020-04-15T20:30:00,light,20 minutes,Occurred : 4/15/2020 20:30 (Entered as : 4/15...,Crazy light show! A series of lights eminating...,2020-06-25T00:00:00,32.259941,-110.927542,2020-04-15,20:30:00
134,Star looking ufo in sky starts to move then di...,Phoenix,AZ,2020-04-12T01:00:00,other,5-7 minutes,Occurred : 4/12/2020 01:00 (Entered as : 04/1...,Star looking ufo in sky starts to move then di...,2020-06-25T00:00:00,33.535381,-112.049460,2020-04-12,01:00:00
145,"Saw a bright, star like object, very high up, ...",Tucson,AZ,2020-03-29T21:00:00,circle,2 hours,Occurred : 3/29/2020 21:00 (Entered as : 03/2...,"Saw a bright, star like object, very high up, ...",2020-06-25T00:00:00,32.259941,-110.927542,2020-03-29,21:00:00
149,Strange shaped craft,Gilbert,AZ,2019-12-13T22:15:00,other,3 minutes,Occurred : 12/13/2019 22:15 (Entered as : 12/...,strange shaped craft I went to my car to pick ...,2020-06-25T00:00:00,33.339601,-111.781265,2019-12-13,22:15:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
136848,Tonopah Arizona lights,Tonopah,AZ,2020-07-23T19:30:00,fireball,1 minute,Occurred : 7/23/2020 19:30 (Entered as : 07/2...,Tonopah Arizona lights It was in the afternoon...,2020-08-06T00:00:00,33.577800,-113.023400,2020-07-23,19:30:00
136866,MADAR Node 74,Show Low,AZ,2020-06-12T13:46:00,NaN,NaN,Occurred : 6/12/2020 13:46 (Entered as : 06/1...,MADAR Node 74,2020-07-09T00:00:00,34.234662,-110.075197,2020-06-12,13:46:00
136883,Tonopah Arizona lights,Tonopah,AZ,2020-07-23T19:30:00,fireball,1 minute,Occurred : 7/23/2020 19:30 (Entered as : 07/2...,Tonopah Arizona lights It was in the afternoon...,2020-07-23T00:00:00,33.577800,-113.023400,2020-07-23,19:30:00
136897,It was about 2:15am to 2:30am I look up in the...,Scottsdale,AZ,2019-07-08T02:15:00,circle,15 min,Occurred : 7/8/2019 02:15 (Entered as : 07/08...,It was about 2:15am to 2:30am I look up in the...,2019-07-25T00:00:00,33.564138,-111.905083,2019-07-08,02:15:00
136909,Ring Light UFO expanding in and out,Gilbert,AZ,2019-04-01T23:00:00,circle,2 minutes,Occurred : 4/1/2019 23:00 (Entered as : 04/01...,Ring Light UFO expanding in and out I was taki...,2021-03-02T00:00:00,33.339601,-111.781265,2019-04-01,23:00:00

In [14]:
newufo_df2 = newufo_df1.drop(["date_time"], axis=1)

In [15]:
newufo_df2

,summary,city,state,shape,duration,stats,text,posted,city_latitude,city_longitude,date_str,time_str
117,Fleet of moving stars. ((Starlink satellites?)),Litchfield Park,AZ,light,1 hour,Occurred : 4/17/2020 20:00 (Entered as : 04/1...,Fleet of moving stars Looked like moving stars...,2020-06-25T00:00:00,33.517800,-112.366700,2020-04-17,20:00:00
125,Crazy light show! ((Starlink satellites?)),Tucson,AZ,light,20 minutes,Occurred : 4/15/2020 20:30 (Entered as : 4/15...,Crazy light show! A series of lights eminating...,2020-06-25T00:00:00,32.259941,-110.927542,2020-04-15,20:30:00
134,Star looking ufo in sky starts to move then di...,Phoenix,AZ,other,5-7 minutes,Occurred : 4/12/2020 01:00 (Entered as : 04/1...,Star looking ufo in sky starts to move then di...,2020-06-25T00:00:00,33.535381,-112.049460,2020-04-12,01:00:00
145,"Saw a bright, star like object, very high up, ...",Tucson,AZ,circle,2 hours,Occurred : 3/29/2020 21:00 (Entered as : 03/2...,"Saw a bright, star like object, very high up, ...",2020-06-25T00:00:00,32.259941,-110.927542,2020-03-29,21:00:00
149,Strange shaped craft,Gilbert,AZ,other,3 minutes,Occurred : 12/13/2019 22:15 (Entered as : 12/...,strange shaped craft I went to my car to pick ...,2020-06-25T00:00:00,33.339601,-111.781265,2019-12-13,22:15:00
...,...,...,...,...,...,...,...,...,...,...,...,...
136848,Tonopah Arizona lights,Tonopah,AZ,fireball,1 minute,Occurred : 7/23/2020 19:30 (Entered as : 07/2...,Tonopah Arizona lights It was in the afternoon...,2020-08-06T00:00:00,33.577800,-113.023400,2020-07-23,19:30:00
136866,MADAR Node 74,Show Low,AZ,NaN,NaN,Occurred : 6/12/2020 13:46 (Entered as : 06/1...,MADAR Node 74,2020-07-09T00:00:00,34.234662,-110.075197,2020-06-12,13:46:00
136883,Tonopah Arizona lights,Tonopah,AZ,fireball,1 minute,Occurred : 7/23/2020 19:30 (Entered as : 07/2...,Tonopah Arizona lights It was in the afternoon...,2020-07-23T00:00:00,33.577800,-113.023400,2020-07-23,19:30:00
136897,It was about 2:15am to 2:30am I look up in the...,Scottsdale,AZ,circle,15 min,Occurred : 7/8/2019 02:15 (Entered as : 07/08...,It was about 2:15am to 2:30am I look up in the...,2019-07-25T00:00:00,33.564138,-111.905083,2019-07-08,02:15:00
136909,Ring Light UFO expanding in and out,Gilbert,AZ,circle,2 minutes,Occurred : 4/1/2019 23:00 (Entered as : 04/01...,Ring Light UFO expanding in and out I was taki...,2021-03-02T00:00:00,33.339601,-111.781265,2019-04-01,23:00:00

In [17]:
# converting to csv
newufo_df2.to_csv('/Users/katiebernstein/Documents/Data Bootcamp/Git/Group1_Final_Project/ufo_data_cleaned4.csv')